#!/bin/sh /etc/rc.common

USE_PROCD=1
# after network
START=50

BASE_DIR=/opt/tun-xray
PROG=$BASE_DIR/start_tun2socks.sh
NAME=tun2socks

start_service() {
	procd_open_instance
	procd_set_param command $PROG up
	procd_set_param pidfile $PIDFILE
    procd_set_param term_signal SIGINT
	procd_close_instance
}

service_stopped()
{
	$PROG down
}

# stop_service()
# {
# 	# this procedure is called from stop()
# 	# stop() already stop daemons
#     # local PID=$(cat $PIDFILE)

#     # if [ "$PID" != "" ]; then
#     #     echo "Waiting for $PID to exit"
#     #     while kill -0 $PID; do 
#     #         sleep 1
#     #     done
#     # fi
#     $PROG down
# }